{
 "title": "MySQL Exporter Dashboard",
 "tags": [
  "StarsL.cn",
  "MySQL",
  "mysqld_exporter",
  "ConsulManager"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "vendor", "query": { "query": "label_values(mysql_up, vendor)" } },
   {
    "name": "account",
    "query": {
     "query": "label_values(mysql_up{vendor=~\"$vendor\"}, account)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(mysql_up{vendor=~\"$vendor\",account=~\"$account\"}, group)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(mysql_up{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\"}, name)"
    }
   },
   {
    "name": "iid",
    "label": "ID",
    "query": {
     "query": "label_values(mysql_up{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\"}, iid)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(mysql_up{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\"}, instance)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,30m,1h,3h,6h,12h,24h,48h,72h,"
   },
   {
    "name": "version",
    "query": {
     "query": "query_result(mysql_version_info{instance=~\"$host\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MySQL ALL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL【$vendor：$account：$group】",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mysql_up{account=~\"$account\",group=~\"$group\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "mysql_cpu_util * on (iid) group_right mysql_up{account=~\"$account\",group=~\"$group\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "mysql_mem_util * on (iid) group_right mysql_up{account=~\"$account\",group=~\"$group\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "mysql_disk_util * on (iid) group_right mysql_up{account=~\"$account\",group=~\"$group\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(mysql_global_status_queries{account=~\"$account\",group=~\"$group\"}[$interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum (mysql_info_schema_processlist_processes_by_user{account=~\"$account\",group=~\"$group\"})by(account,group,name,iid)"
      },
      {
       "expr": "mysql_global_status_threads_running{account=~\"$account\",group=~\"$group\"} -0"
      },
      {
       "expr": "sum (mysql_info_schema_processlist_threads{account=~\"$account\",group=~\"$group\",state!=\"unknown\"}) by(account,group,name,iid)",
       "legendFormat": "unknown"
      },
      {
       "expr": "rate(mysql_global_status_bytes_received{account=~\"$account\",group=~\"$group\"}[$interval])"
      },
      {
       "expr": "rate(mysql_global_status_bytes_sent{account=~\"$account\",group=~\"$group\"}[$interval])"
      },
      {
       "expr": "mysql_iops_count * on (iid) group_right mysql_up{account=~\"$account\",group=~\"$group\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Uptime",
     "type": "stat",
     "description": "mysql。",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_status_uptime{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "Version",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
     "options": {
      "content": "<h3 style='color:#e68a00;font-weight:bold;text-align:center'>$version</h3>"
     }
    },
    {
     "title": "Current QPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(mysql_global_status_queries{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool",
     "type": "stat",
     "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_innodb_buffer_pool_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Row Lock Blocking",
     "type": "stat",
     "description": "Percent of Active Sections which are blocked due to waiting on Innodb Row Locks",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_row_lock_time{instance=~\"$host\"}[$interval])/1000 or irate(mysql_global_status_innodb_row_lock_time{instance=~\"$host\"}[5m])/1000)/((avg_over_time(mysql_global_status_threads_running{instance=~\"$host\"}[$interval]))or (avg_over_time(mysql_global_status_threads_running{instance=~\"$host\"}[5m]))))"
      }
     ]
    },
    {
     "title": "Total Redo Log Space",
     "type": "stat",
     "description": "Number of Innodb Log Files Multiplied by Their Size",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (mysql_global_variables_innodb_log_file_size{instance=~\"$host\"} * mysql_global_variables_innodb_log_files_in_group{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Fsync Rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_data_fsyncs{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{instance=~\"$host\"}[5m])) + ((rate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[5m]))))"
      }
     ]
    },
    {
     "title": "Log Fsync Rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (((rate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[5m]))))"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by () (clamp_max(sum by (instance) ( avg by (mode,instance) ((clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",region=~\".*\",\r\nnode_type=~\"()\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[5m]),1)) or \r\n(clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",region=~\".*\",node_type=~\"()\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[5m]),1)) ) )*100 or \r\n(avg_over_time(node_cpu_average{instance=~\"$host\",region=~\".*\",node_type=~\"()\",mode=\"total\"}[5m]) or \r\navg_over_time(node_cpu_average{instance=~\"$host\",region=~\".*\",node_type=~\"()\",mode=\"total\"}[5m]) or avg_over_time(node_cpu_average{instance=~\"$host\",region=~\".*\",node_type=~\"()\",node_type=\"remote_azure_database\"}[5m]) or \r\navg_over_time(node_cpu_average{instance=~\"$host\",region=~\".*\",node_type=~\"()\",node_type=\"remote_azure_database\"}[5m])),100))",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "avg by () (node_memory_MemTotal_bytes{instance=\"$host\"} - \r\n(node_memory_MemFree_bytes{instance=\"$host\"} + \r\nnode_memory_Buffers_bytes{instance=\"$host\"} + \r\nnode_memory_Cached_bytes{instance=\"$host\"}))",
       "legendFormat": "Used Memory"
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "avg by (instance, mountpoint) (\r\n  max_over_time(\r\n    node_filesystem_size_bytes{\r\n      instance=\"$host\",\r\n      mountpoint=\"/\",\r\n      fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"\r\n    }[5m]\r\n  )\r\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "avg by (instance,mountpoint) (max_over_time(node_filesystem_free_bytes{instance=\"$host\", mountpoint=\"/\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m]) or max_over_time(node_filesystem_free_bytes{instance=\"$host\", mountpoint=\"/\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m]) or (storage_limit_bytes_average{instance=\"$host\"} - azure_storage_used_bytes_average{instance=\"$host\"}))",
       "legendFormat": "Free Disk"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg((sum by (instance) (rate(node_disk_read_time_seconds_total{instance=\"$host\"}[5m]) or \r\nirate(node_disk_read_time_seconds_total{instance=\"$host\"}[5m]))) + \r\n(sum by (instance) (rate(node_disk_write_time_seconds_total{instance=\"$host\"}[5m]) or \r\nirate(node_disk_write_time_seconds_total{instance=\"$host\"}[5m]))) or\r\nsum by (instance) ((max_over_time(rdsos7ySOyIWVk_diskIO_readIOsPS{instance=\"$host\"}[5m]) or max_over_time(rdsos7ySOyIWVk_diskIO_readIOsPS{instance=\"$host\"}[5m])) +\r\n(max_over_time(rdsos7ySOyIWVk_diskIO_writeIOsPS{instance=~\"192\\\\.168\\\\.99\\\\.53\"}[5m]) or max_over_time(rdsos7ySOyIWVk_diskIO_writeIOsPS{instance=\"$host\"}[5m]))))",
       "legendFormat": "IOPS"
      }
     ]
    },
    {
     "title": "Overview of the top 10 tables",
     "type": "table-old",
     "description": "Top10",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "topk(10, sum(mysql_info_schema_table_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\", component!=\"data_free\"}) by (schema, table)) > 0",
       "legendFormat": "{{ schema }}.{{ table }}"
      }
     ]
    },
    {
     "title": "The top 10 tables in terms of data volume",
     "type": "table-old",
     "description": "Top10",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "topk(10, sum(mysql_info_schema_table_rows{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}) by (schema, table)) > 0",
       "legendFormat": "{{ schema }}.{{ table }}"
      }
     ]
    },
    {
     "title": "QPS/TPS",
     "type": "graph",
     "description": "QPS，\n- ：\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none", "label": "QPS" }
     ],
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(mysql_global_status_queries{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "QPS"
      },
      {
       "calculatedInterval": "10m",
       "expr": "sum(rate(mysql_global_status_commands_total{account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$host\",command=~\"(commit|rollback)\"}[$interval])) without (command)",
       "legendFormat": "TPS"
      }
     ]
    },
    {
     "title": "of user connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_info_schema_processlist_processes_by_user{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "{{mysql_user}}"
      }
     ]
    },
    {
     "title": "MySQL Buffer usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": " mysql_global_status_innodb_page_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"} * on (instance) mysql_global_status_buffer_pool_pages{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\",state=\"data\"}",
       "legendFormat": "InnoDB Buffer Pool Data"
      },
      {
       "expr": "mysql_global_variables_innodb_log_buffer_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "InnoDB Log Buffer Size"
      },
      {
       "expr": "mysql_global_variables_innodb_additional_mem_pool_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "InnoDB Additional Memory Pool Size"
      },
      {
       "expr": "mysql_global_status_innodb_mem_dictionary{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "InnoDB Dictionary Size"
      },
      {
       "expr": "mysql_global_variables_key_buffer_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Key Buffer Size"
      },
      {
       "expr": "mysql_global_variables_query_cache_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Query Cache Size"
      },
      {
       "expr": "mysql_global_status_innodb_mem_adaptive_hash{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Adaptive Hash Index Size"
      },
      {
       "expr": "mysql_global_variables_tokudb_cache_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "TokuDB Cache Size"
      }
     ]
    },
    {
     "title": "PROCESSLIST",
     "type": "graph",
     "description": "Processlist",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_info_schema_processlist_threads{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Slow Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow sorting",
     "type": "graph",
     "description": "Sort_scan  Sort_range\n， order by  group by（ order by NULL  group by），：\n where \n\n\n， Sort_scan  Sort_range。 Select_scan， Sort_scan， Select_range， Sort_range。 Sort_scan  Sort_range ，，。\nSort_merge_passes\nSort_merge_passes 。MySQL ， Sort_buffer_size ，，MySQL ， MySQL ，。 Sort_merge_passes。，MySQL ， Sort_merge_passes 。，， Sort_buffer_size  Sort_merge_passes  。 Sort_buffer_size 。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_range{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Sort Range"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_merge_passes{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Sort Merge Passes"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_scan{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Sort Scan"
      }
     ]
    },
    {
     "title": "The number of slow queries per minute",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "delta(mysql_global_status_slow_queries{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[1m])",
       "legendFormat": "Slow Queries per Minute"
      }
     ]
    },
    {
     "title": "Temporary objects",
     "type": "graph",
     "description": "mysql：、。，。。",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_created_tmp_tables{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Temp Tables"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_created_tmp_disk_tables{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Temp Disk Tables"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_created_tmp_files{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Temp Files"
      }
     ]
    },
    {
     "title": "MySQL slow scan type",
     "type": "graph",
     "description": "MySQL",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_full_join{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Full Join"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_full_range_join{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Full Range Join"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_range{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Select Range"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_range_check{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Range Check"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_scan{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Table Scan"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Connections",
     "type": "graph",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_threads_connected{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_max_used_connections{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_max_connections{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "Active connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_threads_running{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "{{instance}} - Threads Running"
      },
      {
       "calculatedInterval": "2m",
       "expr": "delta(mysql_global_status_connection_errors_total{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[1m]) > 0",
       "legendFormat": "{{instance}} - Connection Errors/min"
      }
     ]
    },
    {
     "title": "Thread caching",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_thread_cache_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Thread Cache Size - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_threads_cached{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Threads Cached - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_threads_created{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "\tThreads Created Rate - {{instance}}"
      }
     ]
    },
    {
     "title": "Master-slave replication delay (data is only available from the slave library)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_slave_status_seconds_behind_master{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Slave Delay Seconds - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection break with table lock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB row lock waits",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(mysql_global_status_innodb_row_lock_waits{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[1m])",
       "legendFormat": " Row Lock Waits (1m) - {{instance}}"
      },
      {
       "expr": "delta(mysql_global_status_innodb_row_lock_time{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[1m])/1000",
       "legendFormat": "Row Lock Wait Time (s, 1m) - {{instance}}"
      },
      {
       "expr": "(rate(mysql_global_status_innodb_row_lock_time{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])/1000)/rate(mysql_global_status_innodb_row_lock_waits{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Avg Row Lock Wait Time (s) - {{instance}}"
      }
     ]
    },
    {
     "title": "InnoDB deadlocks every minute",
     "type": "graph",
     "description": "**InnoDB Deadlocks**\n\nA deadlock in MySQL happens when two or more transactions mutually hold and request for locks, creating a cycle of dependencies. In a transaction system, deadlocks are a fact of life and not completely avoidable. InnoDB automatically detects transaction deadlocks, rollbacks a transaction immediately and returns an error.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "delta(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[1m])",
       "legendFormat": "Deadlocks (1m) - {{instance}}"
      },
      {
       "expr": "mysql_global_variables_innodb_print_all_deadlocks{hostname=\"baoquan-master\"}",
       "legendFormat": "innodb_print_all_deadlocks - {{hostname}}"
      }
     ]
    },
    {
     "title": "Broken connections",
     "type": "graph",
     "description": "mysql，（），mysql。\n\nmax_connect_errors，mysqld。\n\n，“flush hosts”。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_connects{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Aborted Connects Rate - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_clients{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Aborted Clients Rate - {{instance}}"
      }
     ]
    },
    {
     "title": "Table lock",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_table_locks_immediate{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Table Locks Immediate Rate - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_table_locks_waited{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Table Locks Waited Rate - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Command, Handlers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Command Counters",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(mysql_global_status_commands_total{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    },
    {
     "title": "Handlers",
     "type": "graph",
     "description": "- read_rnd_next：。，。。\n- read_next：。，。\n- read_key：。，。\n- write：。 \n- read_rnd：。。MySQL。\n- external_lock：，。\n- update：。 \n- read_prev：。ORDER BY … DESC。\n- read_first：。，；，SELECT col1 FROM foo，col1。\n- delete：。\n- read_last：。",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_handlers_total{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval])",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "MySQL Transaction Handlers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_handlers_total{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval])",
       "legendFormat": "{{ handler }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transfer speed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_received{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Bytes Received Rate - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_sent{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Bytes Sent Rate - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL hourly traffic usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_bytes_received{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[1h])",
       "legendFormat": "Bytes Received (1h) - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_bytes_sent{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[1h])",
       "legendFormat": "Bytes Sent (1h) - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB Buffer Pool Hit Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- mysql_global_status_innodb_buffer_pool_reads{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"} / mysql_global_status_innodb_buffer_pool_read_requests{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"} ",
       "legendFormat": "InnoDB Buffer Pool Hit Rate - {{instance}}"
      }
     ]
    },
    {
     "title": "Cache usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_qcache_hits{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Query Cache Hits Rate - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_qcache_inserts{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Query Cache Inserts Rate - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_qcache_not_cached{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Query Cache Not Cached Rate - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_qcache_lowmem_prunes{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Query Cache Low Memory Prunes Rate - {{instance}}"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Read Requests"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_buffer_pool_write_requests{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Write Requests"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_buffer_pool_reads{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Disk Reads"
      }
     ]
    },
    {
     "title": "Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_qcache_free_memory{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Query Cache Free Memory - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_query_cache_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Query Cache Size - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Table Definition Cache",
     "type": "graph",
     "description": "**MySQL Table Definition Cache**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_open_table_definitions{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Open Table Definitions"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_table_definition_cache{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Table Definitions Cache Size"
      },
      {
       "expr": "rate(mysql_global_status_opened_table_definitions{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Opened Table Definitions"
      }
     ]
    },
    {
     "title": "MySQL Table Open Cache Status",
     "type": "graph",
     "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_opened_tables{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Openings"
      },
      {
       "expr": "rate(mysql_global_status_table_open_cache_hits{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Hits"
      },
      {
       "expr": "rate(mysql_global_status_table_open_cache_misses{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Misses"
      },
      {
       "expr": "rate(mysql_global_status_table_open_cache_overflows{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Misses due to Overflows"
      },
      {
       "expr": "rate(mysql_global_status_table_open_cache_hits{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])/(rate(mysql_global_status_table_open_cache_hits{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])+rate(mysql_global_status_table_open_cache_misses{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval]))",
       "legendFormat": "Table Open Cache Hit Ratio"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Content",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_innodb_buffer_pool_bytes_data{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Data Total"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_innodb_buffer_pool_bytes_dirty{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Data Dirty"
      }
     ]
    }
   ]
  },
  {
   "title": "Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL File Openings",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_opened_files{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Openings"
      }
     ]
    },
    {
     "title": "MySQL Open Files",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_open_files{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Open Files"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_open_files_limit{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Open Files Limit"
      },
      {
       "expr": "mysql_global_status_innodb_num_open_files{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "InnoDB Open Files"
      }
     ]
    },
    {
     "title": "InnoDB Row Operations",
     "type": "graph",
     "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_row_ops_total{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Rows {{ operation }}"
      }
     ]
    },
    {
     "title": "MySQL Open Tables",
     "type": "graph",
     "description": "**MySQL Open Tables**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_open_tables{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Open Tables"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_table_open_cache{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Table Open Cache"
      }
     ]
    },
    {
     "title": "InnoDB I/O",
     "type": "graph",
     "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_data_reads{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Data Reads"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_data_writes{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Data Writes"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_data_fsyncs{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Data Fsyncs"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_log_writes{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[$interval])",
       "legendFormat": "Log Writes"
      }
     ]
    },
    {
     "title": "InnoDB Log File Usage Hourly",
     "type": "graph",
     "description": "**InnoDB Log File Usage Hourly**\n\nAlong with the buffer pool size, `innodb_log_file_size` is the most important setting when we are working with InnoDB. This graph shows how much data was written to InnoDB's redo logs over each hour. When the InnoDB log files are full, InnoDB needs to flush the modified pages from memory to disk.\n\nThe rules of the thumb is to keep one hour of traffic in those logs and let the checkpointing perform its work as smooth as possible. If you don't do this, InnoDB will do synchronous flushing at the worst possible time, ie when you are busiest.\n\nThis graph can help guide you in setting the correct `innodb_log_file_size`.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_innodb_os_log_written{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}[1h])",
       "legendFormat": "Data Written"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_innodb_log_files_in_group{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"} * mysql_global_variables_innodb_log_file_size{account=~\"$account\",group=~\"$group\",name=~\"$name\",iid=~\"$iid\",instance=~\"$host\"}",
       "legendFormat": "Total Size of InnoDB Log Files"
      }
     ]
    }
   ]
  },
  {
   "title": "InnoDB Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB Page Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_status_innodb_page_size{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Avg Data Read Rq Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_data_read{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_read{instance=~\"$host\"}[5m]))/(rate(mysql_global_status_innodb_data_reads{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{instance=~\"$host\"}[5m])))"
      }
     ]
    },
    {
     "title": "Avg Data Write Rq Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[5m]))/(rate(mysql_global_status_innodb_data_writes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{instance=~\"$host\"}[5m])))"
      }
     ]
    },
    {
     "title": "Avg Log Write Rq Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_os_log_written{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{instance=~\"$host\"}[5m]))/(rate(mysql_global_status_innodb_log_writes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_log_writes{instance=~\"$host\"}[5m])))"
      }
     ]
    },
    {
     "title": "Data Written Per Fsync",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[5m]))/(rate(mysql_global_status_innodb_data_fsyncs{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{instance=~\"$host\"}[5m])))"
      }
     ]
    },
    {
     "title": "Log Written Per Fsync",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_os_log_written{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{instance=~\"$host\"}[5m]))/(rate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[5m])))"
      }
     ]
    },
    {
     "title": "Data Read Per Row Read",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum((rate(mysql_global_status_innodb_data_read{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_read{instance=~\"$host\"}[5m])))/ sum((rate(mysql_global_status_innodb_row_ops_total{instance=~\"$host\",operation=\"read\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=~\"$host\",operation=\"read\"}[5m])))"
      }
     ]
    },
    {
     "title": "Data Written Per Row Written",
     "type": "stat",
     "description": "Note: Due to difference in timing of Row Write and Data Write the value may be misleading on short intervals",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(rate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[$interval]))/sum(rate(mysql_global_status_innodb_row_ops_total{instance=~\"$host\",operation!=\"read\"}[$interval]))  or sum(irate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[5m]))/sum(irate(mysql_global_status_innodb_row_ops_total{instance=~\"$host\",operation!=\"read\"}[5m]))\r\n"
      }
     ]
    },
    {
     "title": "InnoDB Data I/O",
     "type": "graph",
     "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_data_reads{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{instance=~\"$host\"}[5m]))",
       "legendFormat": "Data Reads"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_data_writes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{instance=~\"$host\"}[5m]))",
       "legendFormat": "Data Writes"
      },
      {
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_data_reads{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{instance=~\"$host\"}[5m]))+ (rate(mysql_global_status_innodb_data_writes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{instance=~\"$host\"}[5m])))",
       "legendFormat": "Data Total IOPS"
      }
     ]
    },
    {
     "title": "InnoDB Data Bandwitdh",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_data_read{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_read{instance=~\"$host\"}[5m]))",
       "legendFormat": "Data Read"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[5m]))",
       "legendFormat": "Data Written"
      },
      {
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_data_read{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_read{instance=~\"$host\"}[5m]))+ (rate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_written{instance=~\"$host\"}[5m])))",
       "legendFormat": "Data Total Bandwith"
      }
     ]
    },
    {
     "title": "InnoDB Log IO",
     "type": "graph",
     "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_log_writes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_log_writes{instance=~\"$host\"}[5m]))",
       "legendFormat": "Log Writes"
      },
      {
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_os_log_written{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{instance=~\"$host\"}[5m]))",
       "legendFormat": "Log Written"
      }
     ]
    },
    {
     "title": "InnoDB FSyncs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_data_fsyncs{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{instance=~\"$host\"}[5m]))",
       "legendFormat": "Data Fsyncs"
      },
      {
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[5m]))",
       "legendFormat": "Log Fsyncs"
      }
     ]
    },
    {
     "title": "InnoDB Pending IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (avg_over_time(mysql_global_status_innodb_data_pending_reads{instance=~\"$host\"}[$interval]) or\navg_over_time(mysql_global_status_innodb_data_pending_reads{instance=~\"$host\"}[5m]))",
       "legendFormat": "Pending Data Reads"
      },
      {
       "expr": "avg by (instance) (avg_over_time(mysql_global_status_innodb_data_pending_writes{instance=~\"$host\"}[$interval]) or\navg_over_time(mysql_global_status_innodb_data_pending_writes{instance=~\"$host\"}[5m]))",
       "legendFormat": "Pending Data Writes"
      },
      {
       "expr": "avg by (instance) (avg_over_time(mysql_global_status_innodb_os_log_pending_writes{instance=~\"$host\"}[$interval]) or\navg_over_time(mysql_global_status_innodb_os_log_pending_writes{instance=~\"$host\"}[5m]))",
       "legendFormat": "Pending Log Writes"
      }
     ]
    },
    {
     "title": "InnoDB Pending Fsyncs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (instance) (avg_over_time(mysql_global_status_innodb_os_log_pending_fsyncs{instance=~\"$host\"}[$interval]) or\navg_over_time(mysql_global_status_innodb_os_log_pending_fsyncs{instance=~\"$host\"}[5m]))",
       "legendFormat": "Pending Log Fsyncs"
      }
     ]
    },
    {
     "title": "InnoDB Auto Extend Increment",
     "type": "stat",
     "description": "When Growing Innodb System Tablespace extend it by this size at the time",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_autoextend_increment{instance=~\"$host\"}*1024*1024)"
      }
     ]
    },
    {
     "title": "InnoDB Double Write",
     "type": "stat",
     "description": "Is InnoDB Double Write Buffer Enabled ?  Doing so doubles amount of writes InnoDB has to do to storage but is required to avoid potential data corruption during the crash on most storage subsystems",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_doublewrite{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB Fast Shutdown",
     "type": "stat",
     "description": "Fast Shutdown means InnoDB will not perform complete Undo Space and Change Buffer cleanup on shutdown, which is faster but may interfere with certain major upgrade operations",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_fast_shutdown{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB Open Files",
     "type": "stat",
     "description": "Maximum Number of Files InnoDB is Allowed to use",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_open_files{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB File Use",
     "type": "stat",
     "description": "Portion of Allowed InnoDB Open Files Use",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(mysql_global_status_innodb_num_open_files{instance=~\"$host\"})/sum(mysql_global_variables_innodb_open_files{instance=~\"$host\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Pool Size ",
     "type": "stat",
     "description": "**InnoDB Buffer Pool Size **\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_buffer_pool_size{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Buffer Pool Size of Total RAM",
     "type": "stat",
     "description": "**InnoDB Buffer Pool Size % of Total RAM**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) ((mysql_global_variables_innodb_buffer_pool_size{instance=~\"$host\"} * 100)) / \non (node_name) (avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "NUMA Interleave",
     "type": "stat",
     "description": "Interleave Buffer Pool between NUMA zones to better support NUMA systems",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_numa_interleave{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Buffer Pool Activity",
     "type": "stat",
     "description": "Combined value of Buffer Pool Read and Write reuests",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_buffer_pool_write_requests{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{instance=~\"$host\"}[5m]))"
      }
     ]
    },
    {
     "title": "BP Data ",
     "type": "stat",
     "description": "Percent of Buffer Pool Occupied by Cached Data",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(avg_over_time(mysql_global_status_buffer_pool_pages{instance=~\"$host\", state=\"data\"}[5m]))/sum(avg_over_time(mysql_global_status_buffer_pool_pages{instance=~\"$host\", state=\"total\"}[5m]))"
      }
     ]
    },
    {
     "title": "BP Data Dirty",
     "type": "stat",
     "description": "Percent of Data which is Dirty",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(avg_over_time(mysql_global_status_buffer_pool_pages{instance=~\"$host\", state=\"dirty\"}[5m]))/sum(avg_over_time(mysql_global_status_buffer_pool_pages{instance=~\"$host\", state=\"data\"}[5m]))"
      }
     ]
    },
    {
     "title": "BP Miss Ratio",
     "type": "stat",
     "description": "How often buffer pool read requests have to do read from the disk. Keep this percent low for good performance",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_buffer_pool_reads{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_reads{instance=~\"$host\"}[5m])) / (rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$host\"}[5m])))"
      }
     ]
    },
    {
     "title": "BP Write Buffering",
     "type": "stat",
     "description": "Number of Logical Writes to Buffer Pool Per logical Write",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_buffer_pool_write_requests{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{instance=~\"$host\"}[5m]))/(rate(mysql_global_status_innodb_data_writes{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{instance=~\"$host\"}[5m])))"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance,state) (avg_over_time(mysql_global_status_buffer_pool_pages{instance=~\"$host\", state=~\"free|data|misc\"}[$interval]) or\navg_over_time(mysql_global_status_buffer_pool_pages{instance=~\"$host\", state=~\"free|data|misc\"}[5m]))",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Data ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{instance=~\"$host\"}[$interval]) or\navg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{instance=~\"$host\"}[5m]))",
       "legendFormat": "Data Total"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_dirty{instance=~\"$host\"}[$interval]) or\navg_over_time(mysql_global_status_innodb_buffer_pool_bytes_dirty{instance=~\"$host\"}[5m]))",
       "legendFormat": "Data Dirty"
      },
      {
       "expr": "avg by (instance) (sum((avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{instance=~\"$host\"}[$interval]) or\navg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{instance=~\"$host\"}[5m])))*sum(mysql_global_variables_innodb_max_dirty_pages_pct{instance=~\"$host\"})/100)",
       "legendFormat": "Estimated Dirty Data Limit"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Page Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_pages_created{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_created{instance=~\"$host\"}[5m]))",
       "legendFormat": "Pages Created"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_pages_read{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{instance=~\"$host\"}[5m]))",
       "legendFormat": "Pages Read"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_pages_written{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_written{instance=~\"$host\"}[5m]))",
       "legendFormat": "Pages Written"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$host\"}[5m]))",
       "legendFormat": "Read Requests"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_buffer_pool_write_requests{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{instance=~\"$host\"}[5m]))",
       "legendFormat": "Write Requests"
      }
     ]
    },
    {
     "title": "InnoDB Read-Ahead",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=~\"$host\"}[5m]))",
       "legendFormat": "Pages Fetched by Linear Read Ahead "
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=~\"$host\"}[5m]))",
       "legendFormat": "Paged Fetched by Random Read Ahead"
      },
      {
       "expr": "avg by (instance) (rate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{instance=~\"$host\"}[5m]))",
       "legendFormat": "Paged Fetched by Read Ahead but Never Accessed"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool LRU Sub-Chain Churn",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_buffer_pool_page_changes_total_pool_page_changes_total{instance=~\"$host\", operation=\"made_young\"}[$interval]) or irate(mysql_global_status_buffer_pool_page_changes_total{instance=~\"$host\", operation=\"made_young\"}[5m]))",
       "legendFormat": "Buffer Pool Pages Made Young"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (instance) (rate(mysql_global_status_buffer_pool_page_changes_total_pool_page_changes_total{instance=~\"$host\", operation=\"made_not_young\"}[$interval]) or irate(mysql_global_status_buffer_pool_page_changes_total{instance=~\"$host\", operation=\"made_not_young\"}[5m]))",
       "legendFormat": "Buffer Pool Pages Made Not Young"
      }
     ]
    },
    {
     "title": "Buffer Pool Chunk Size",
     "type": "stat",
     "description": "Size of the \"Chunk\" for buffer pool allocation.  Allocation of buffer pool will be rounded by this number. It also affects the performance impact of online buffer pool resize",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_buffer_pool_chunk_size{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Buffer Pool Instances",
     "type": "stat",
     "description": "Number of Buffer Pool Instances. Higher values allow to reduce contention but also increase overhead",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_buffer_pool_instances{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Read Ahead IO Percent",
     "type": "stat",
     "description": "Percent of Reads Caused by Innodb Read Ahead",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (((rate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=~\"$host\"}[5m]))+(rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=~\"$host\"}[5m])))/(rate(mysql_global_status_innodb_pages_read{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{instance=~\"$host\"}[5m])\n))"
      }
     ]
    },
    {
     "title": "Read Ahead Wasted",
     "type": "stat",
     "description": "Percent of Pages Fetched by Read Ahead Evicted Without Access",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) ((rate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{instance=~\"$host\"}[5m])) / ((rate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=~\"$host\"}[5m])) + (rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=~\"$host\"}[5m]))))"
      }
     ]
    },
    {
     "title": "Dump Buffer Pool on Shutdown",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_buffer_pool_dump_at_shutdown{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Load Buffer Pool at Startup",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_buffer_pool_load_at_startup{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Portion of Buffer Pool To Dump/Load",
     "type": "stat",
     "description": "Larger Portion increases dump/load time but get more of original buffer pool content and hence may reduce warmup time.",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_buffer_pool_dump_pct{instance=~\"$host\"}/100)"
      }
     ]
    },
    {
     "title": "Include Buffer Pool in Core Dump",
     "type": "stat",
     "description": "Whenever to Include Buffer Pool in Crash Core Dumps.  Doing so may dramatically increase core dump file slow down restart.  Only makes a difference if core dumping on crash is enabled",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_buffer_pool_in_core_file{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB Old Blocks ",
     "type": "stat",
     "description": "Percent of The Buffer Pool To be Reserved for \"Old Blocks\" - which has been touched repeatedly over period of time",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_old_blocks_pct{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB Old Blocks Time",
     "type": "stat",
     "description": "The Time which has to pass between multiple touches for the block for it to qualify as old block",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_old_blocks_time{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB Random Read Ahead",
     "type": "stat",
     "description": "Is InnoDB Random ReadAhead Enabled",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_random_read_ahead{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB Random Read Ahead",
     "type": "stat",
     "description": "The Threashold (in Pages) to trigger Linear Read Ahead",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_read_ahead_threshold{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB Read IO Threads",
     "type": "stat",
     "description": "Number of Threads used to Schedule Reads",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_read_io_threads{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB Write IO Threads",
     "type": "stat",
     "description": "Number of Threads used to Schedule  Writes",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_write_io_threads{instance=~\"$host\"})"
      }
     ]
    },
    {
     "title": "InnoDB Native AIO Enabled",
     "type": "stat",
     "description": "Is Native Asynchronous IO enabled ?  Strongly recommended for optimal performance",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (instance) (mysql_global_variables_innodb_use_native_aio{instance=~\"$host\"})"
      }
     ]
    }
   ]
  }
 ]
}